apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: acme-letsencrypt-staging
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: you@your-hostname
    privateKeySecretRef:
      name: acme-letsencrypt-staging
    http01: {}
